## ModuleNotFoundError
- 설치되어 있지 않은 라이브러리를 불러올 때 발생하는 에러
  + 해결방법
    - 실행한 가상환경에 맡게 불러오고자 하는 라이브러리를 설치한 후 가상환경을 재실행하여 import 한다.

In [1]:
import streamlit as st

print(st.__version__)


ModuleNotFoundError: No module named 'streamlit'

In [2]:
import numpy as np

print(np.__version__)

1.26.2


In [4]:
# 리스트의 덧셈
num1 = [1, 2, 3, 4]
num2 = [3, 4, 5, 6]

num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [5]:
# numpy array를 이용하여 덧셈하기
arr1 = np.array(num1)
arr2 = np.array(num2)

arr1 + arr2

array([ 4,  6,  8, 10])

In [9]:
# 정수와 실수가 혼합된 배열 생성
data1 = [1, 2.0, 4, 5, 6.3]
mixedArr1 = np.array(data1)

# numpy는 기본적으로 float을 지원하므로
# 정수도 실수형태로 출력되게 된다
mixedArr1.dtype

dtype('float64')

In [13]:
# 정수로 데이터를 만들기
intData1 = [1, 3, 4, 5, 6]
intArr1 = np.array(intData1, dtype = int)

# 출력결과 정수형태로 데이터가 생성된 것을 확인할 수 있다
# 주의사항으로 실수 데이터가 포함되어있는 경우 dtype을 정수로 하게 되면
# 소수점 아래 데이터가 손실되므로 사용에 유의해야 한다/
print(intArr1.dtype)
intArr1

int64


array([1, 3, 4, 5, 6])

## Numpy 배열 생성
- 1차원, 2차원 등의 다차원 배열 생성 가능

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10) # 1치원 배열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# 1차원 배열을 2차원으로 변경
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# np.arange(12).reshape(4, 5)
# 에러 발생 원소의 개수와 shape이 일치하지 않기 때문

In [22]:
np.arange(12).reshape(4, 1, 3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [27]:
arr3 = np.arange(12).reshape(2, 2, 3)
# arr3의 차원 출력
arr3.shape

(2, 2, 3)

In [30]:
arr2 = np.arange(12).reshape(4, 3)

# 2차원 데이터의 차원 출력
arr2.shape

(4, 3)

### 위에서 사용한 shape 함수의 경우 pandas에서도 동일하게 사용한다
- 출력형태는 "튜플"형태로 나오는 것을 확인할 수 있다

In [33]:
arr1 = np.array([1, 2, 3, 4])

# 1차원 데이터의 차원 출력
arr1.shape

(4,)

In [35]:
# 범위의 시작과 끝 정하고 배열 생성
# 0부터 10까지 원소의 개수를 5개로 하여 동일한 간격으로 떨어져 있는
# 배열 생성
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
# numpy에서 지원하는 pi(원주율)을 이용하여 끝을 지정
# 20개의 원소가 동일한 간격으로 만들어짐 (pi 까지)
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [38]:
# np.zeros()
# 원소를 모두 0으로 채운 배열을 생성한다
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
# np.ones()
# 원소를 모두 1로 채운 배열을 생성한다
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [41]:
# 단위행렬
# n x n인 정사각형 행렬에서 주 대각선이 모두 1이고 
# 나머지는 0인 행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr_I.shape

(3, 3)

In [44]:
np.array(['1.5', '0.62'])

array(['1.5', '0.62'], dtype='<U4')

In [48]:
# astype() # pandas에서 사용 가능

# 문자열 데이터('<U44') 생성
arr = np.array(['1.5', '0.62'])

# 문자열 데이터 float으로 변환
num_arr = arr.astype(float)

# 변환한 데이터의 타입 출력
num_arr.dtype

np.array(['1.5', '0.62'], dtype = float)

array([1.5 , 0.62])

### 실수와 정수가 혼합되어 있는 데이터의 정수 변환
- astype(int) or dtype = int로 가능
- 주의해야 할 점
  + 소수점 이하가 유실되므로 사용시 유의해야 한다

In [50]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1

array([10, 21,  0,  4,  5])

### 난수 배열의 생성
- 난수 : 무작위로 숫자를 추출
  + 사용법
    + a~b 사이의 무작위 정수 x개 :
        Ex)np.random.randint(2, 10, 3)
    + 0~1 사이의 무작위 실수 n x m :
      Ex) np.random.rand(2, 3)

In [55]:
# 0~1 사이의 실수 난수 2 x 3 발생
np.random.rand(2, 3)

array([[0.16105969, 0.55426541, 0.78523115],
       [0.45985848, 0.06812574, 0.89260059]])

In [10]:
# int type 2 ~ 10 사이의 난수 3개 발생
np.random.randint(2, 10, 3)

array([7, 9, 9])

## numpy 라이브러리 random 클래스를 이용하여 로또 번호 생성기 만들기

### 첫번째 방법
- np.random.choice() 메서드 사용
  + 메소드 설명
    range를 주어 1부터 30까지 1개씩 중복이 없도록 생성한다. replace=False 옵션에서 가능
      + Ex) lotto_numbers = np.random.choice(range(1, 30), user_input, replace=False)

### 두번째 방법
- while 문을 통해 유저가 입력한 개수만큼 반복하여 빈 리스트에 추가
  + not in 조건으로 중복 체크 후 리스트에 추가
  + 이후 user_input의 값을 줄여서 조건 체크

In [13]:
# 1 ~ 30 까지의 로또 번호 생성
# 1. np.random.choice() 메서드 사용
user_input = int(input('원하는 로또 번호 개수를 입력해주세요: '))

lotto_numbers = np.random.choice(range(1, 30), user_input, replace=False)
print('======== Creating Lotto Numbers ========')
print(f'생성된 로또 번호는 : {lotto_numbers} 입니다 !')

원하는 로또 번호 개수를 입력해주세요:  6


======== Creating Lotto Numbers ========
생성된 로또 번호는 : [11 26 17  4 13 14] 입니다 !


In [14]:
user_input = int(input('원하는 로또 번호 개수를 입력해주세요: '))
lotto_numbers = []

while user_input > 0:
    # NumPy 배열에서 첫 번째 요소 추출
    lotto_num = np.random.randint(1, 30, 1)[0]  
    if lotto_num not in lotto_numbers:
        lotto_numbers.append(lotto_num)
        user_input -= 1

print('======== Creating Lotto Numbers ========')
print(f'생성된 로또 번호는 : {lotto_numbers} 입니다 !')


원하는 로또 번호 개수를 입력해주세요:  6


======== Creating Lotto Numbers ========
생성된 로또 번호는 : [10, 8, 20, 1, 2, 25] 입니다 !


## 배열의 연산
 - p.225

In [15]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

# 덧셈
print(arr1 + arr2)

# 뺄셈
print(arr1 - arr2)

# 곱셈
print(arr1 * arr2)

# 나눗셈
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### 배열의 비교 연산
- 추후 pandas 데이터 가공할 때 행 추출시 사용

In [17]:
arr1 > 20

array([False, False,  True,  True])

## 통계 연산
- Numpy : 합, 평균, 표준 편차, 분산 등의 기술통계량(descriptive Statistics) 메서드를 제공해줌
  + 기술통계량(descriptive Statistics) : 현재 데이터 상태를 표현(= 묘사, Describe)한다
- 통계 : 평균이 전부다 ! (Mean is Everything)

In [18]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [21]:
# 합
arr3.sum()

10

In [22]:
# 평균
arr3.mean()

2.0

In [23]:
# 표준편차
arr3.std()

1.4142135623730951

In [24]:
# 분산
arr3.var()

2.0

## 누적합과 누적곱
- cumsum() : 누적합
- cumprod() : 누적곱

In [25]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [28]:
# 누적합
arr4.cumsum()

array([ 1,  3,  6, 10])

In [29]:
# 누적곱
arr4.cumprod()

array([ 1,  2,  6, 24])

## 행렬연산
- 선형 대수(Linear Algebra)를 위한 2차원 배열 연산도 지원
  + 행렬곱 : A.dot(B) or np.dot(A, B)
  + 전치행렬 : A.transpose() or np.transpos(A)
  + 역행렬 : np.linalg.inv(A)
  + 행렬식 : np.linalg.det(A)

In [31]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [32]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [39]:
# (1) 행렬곱 계산
A.dot(B)

array([[0, 1],
       [6, 7]])

In [40]:
# (2) 행렬곱 계산 
np.dot(A, B)

array([[0, 1],
       [6, 7]])

In [36]:
# 전치행렬
A.transpose()

array([[0, 2],
       [1, 3]])

In [37]:
# 역행렬
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [38]:
# 행렬식
np.linalg.det(A)

-2.0

## 배열의 인덱싱과 슬라이싱
- string, list, tuple과 동일한 방법으로 접근

In [42]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [43]:
a1[0]

0

In [44]:
a1[4]

40

In [45]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [51]:
# 1차원 배열 : 여러 개의 원소를 선택
# 배열명[[위치1, 위치2, ..., 위치n]]

# 리스트를 인덱스를 통해 접근
a1[[1, 3, 4]]

array([10, 30, 40])

In [52]:
# 2차원 배열 : 특정 위치의 원소 선택
# 배열명[행_위치, 열_위치]

In [61]:
# 10부터 100까지 10씩 더한 원소로 구성된 3 x 3 배열 생성
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [55]:
# (2, 2) 원소의 값을 95로 변경
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [57]:
# 1번 인덱스(두번째 행)의 행 출력
a2[1]

array([40, 50, 60])

In [62]:
# 1번 인덱스(두번째 행)의 원소 값 변경
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 90]])

### 2차원 배열의 여러 원소 선택
- 배열명[[행_위치1, 행_위치2, ..., 행_위치n], [열_위치1, 열_위치2, ..., 열_위치n]]

In [65]:
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 90]])

In [67]:
# (0, 0) (2, 1) 원소 출력
a2[[0, 2], [0, 1]]

array([10, 80])

### 2차원 배열의 조건을 지정해 배열 선택
- 배열명[조건]

In [68]:
a = np.array([1, 2, 3, 4, 5, 6])

# 배열 a의 원소 중 3보다 큰 원소 선택
a[a > 3]

array([4, 5, 6])

In [108]:
# 베열 a의 원소 중 짝수 출력
a[a % 2 == 0]

array([2, 4, 6])

In [109]:
# 배열 a의 원소 중 홀수 출력
a[a % 2 != 0]

array([1, 3, 5])

## 배열의 슬라이싱
- 배열[시작_위치:끝_위치]
- 반환되는 원소의 범위 : '시작_위치 ~ 끝_위치 - 1'

In [79]:
b1 = np.array([0, 10, 20, 30, 40, 50])

# 1번 인덱스부터 3번 인덱스까지의 값 출력
b1[1:4]

array([10, 20, 30])

In [80]:
# 0번 인덱스(처음)부터 2번 인덱스까지의 값 출력
b1[:3]

array([ 0, 10, 20])

In [81]:
# 2번 인덱스부터 마지막 인덱스(끝)까지의 값 출력
b1[2:]

array([20, 30, 40, 50])

In [84]:
# step을 지정하여 원소 값 출력
# 처음부터 끝까지 2 step씩 건너뛰며 출력
b1[::2]

array([ 0, 20, 40])

### 슬라이싱을 이용해 배열의 원소 값 변경하기

In [87]:
# 2번 인덱스부터 4번 인덱스까지의 값을 변경
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [90]:
# 특정 부분을 하나의 값으로 변경하기
# 3번 인덱스부터 5번 인덱스(마지막)까지의 값을 60으로 변경
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

### 2차원 배열(행렬) 슬라이싱
- 사용법
  + 배열[행_시작_위치:행_끝_위치], [열_시작_위치:열_끝_위치]
  + 반환되는 원소의 행 범위 : '행_시작_위치 ~ 행_끝_위치-1'
  + 반환되는 원소의 열 범위 : '열_시작_위치 ~ 열_끝_위치-1'
 
- 특정 행을 선택한 후 열을 슬라이싱 하기
  + 배열[행_위치][열_시작_위치:열_끝_위치]

In [100]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [101]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [102]:
# 행 범위 : 0(처음) ~ 2(마지막)
# 열 범위 : 1 ~ 2(마지막)
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [103]:
# 헹 = 1로 고정
# 열 범위 : 0(처음) ~ 1
# 즉, (1, 0), (1, 1) 출력
b2[1][0:2]

array([40, 50])

In [104]:
# 행 범위 : 0(처음) ~ 1
# 열 범위 : 1 ~ 2(마지막)
# 즉, (0, 1), (0, 2), (1, 1), (1, 2) 값 변경
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

## Numpy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건문

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90
# 조건이 하나인 경우 where로 처리
np.where(arr < 5, arr, arr*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [13]:
# 100, 101, 2, 3, 4, 5, 12, 14, 16, 18
# 2 미만 일 때는 100을 더함
# 5 초과인경우 2를 곱함

# 조건식과 대응되는 결과를 리스트로 만들기
# 조건식에 대응되는 리스트
cond_list = [arr > 5, arr < 2]

# 조건식에 해당하는 원소의 결과값에 대한 리스트
choice_list = [arr * 2, arr + 100]

# default인 경우(= 조건에 해당하지 않는 경우)
np.select(cond_list, choice_list, default=arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

In [4]:
# numpy fill() 메소드
# Ex) a.fill(?): a라는 객체(ndarray)의 값들을 모두 ?의 값으로 채움
a = np.array([1, 2, 3, 4])
a.fill(-4.8)
a

array([-4, -4, -4, -4])

In [7]:
# 위 예시에서 .8이 생략된 이유는 배열 a의 dtype이  int(정수형)이기 때문
b = np.array([1.0, 2.0, 3.0, 4.0])
b.dtype

dtype('float64')

In [12]:
b.fill(-4.8)
b

array([-4.8, -4.8, -4.8, -4.8])

In [14]:
c = np.arange(12).reshape(2, 2, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [16]:
# numpy size
# 몇 개의 원소(메모리 주소)가 할당되었는 지 알 수 있음
c.size

12

In [15]:
# numpy ndim
# 몇 차원 array인지 알 수 있음
c.ndim # 3차원

3